const filledLargeButtons = [
  {
    size: 'large',
    label: 'Button',
    type: 'primary',
    state: 'filled',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'secondary',
    state: 'filled',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'success',
    state: 'filled',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'warning',
    state: 'filled',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'danger',
    state: 'filled',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'primary',
    state: 'hover',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'secondary',
    state: 'hover',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'success',
    state: 'hover',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'warning',
    state: 'hover',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'danger',
    state: 'hover',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'primary',
    state: 'active',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'secondary',
    state: 'active',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'success',
    state: 'active',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'warning',
    state: 'active',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'danger',
    state: 'active',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'primary',
    state: 'focus',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'secondary',
    state: 'focus',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'success',
    state: 'focus',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'warning',
    state: 'focus',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'danger',
    state: 'focus',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'primary',
    state: 'default',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'secondary',
    state: 'default',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'success',
    state: 'default',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'warning',
    state: 'default',
  },
  {
    size: 'large',
    label: 'Button',
    type: 'danger',
    state: 'default',
  },
];

export default filledLargeButtons;
