const filledMediumButtons = [
    {
        size: 'medium',
        label: 'Button',
        type: 'primary',
        state: 'filled',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'secondary',
        state: 'filled',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'success',
        state: 'filled',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'warning',
        state: 'filled',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'danger',
        state: 'filled',
    }, 
    {
        size: 'medium',
        label: 'Button',
        type: 'primary',
        state: 'hover',
    }, 
    {
        size: 'medium',
        label: 'Button',
        type: 'secondary',
        state: 'hover',
    },   
    {
        size: 'medium',
        label: 'Button',
        type: 'success',
        state: 'hover',
    },   
    {
        size: 'medium',
        label: 'Button',
        type: 'warning',
        state: 'hover',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'danger',
        state: 'hover',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'primary',
        state: 'active',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'secondary',
        state: 'active',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'success',
        state: 'active',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'warning',
        state: 'active',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'danger',
        state: 'active',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'primary',
        state: 'focus',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'secondary',
        state: 'focus',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'success',
        state: 'focus',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'warning',
        state: 'focus',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'danger',
        state: 'focus',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'primary',
        state: 'default',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'secondary',
        state: 'default',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'success',
        state: 'default',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'warning',
        state: 'default',
    },
    {
        size: 'medium',
        label: 'Button',
        type: 'danger',
        state: 'default',
    },
]

export default filledMediumButtons;
