const filledSmallButtons = [
  {
    size: 'small',
    label: 'Button',
    type: 'primary',
    state: 'filled',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'secondary',
    state: 'filled',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'success',
    state: 'filled',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'warning',
    state: 'filled',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'danger',
    state: 'filled',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'primary',
    state: 'hover',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'secondary',
    state: 'hover',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'success',
    state: 'hover',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'warning',
    state: 'hover',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'danger',
    state: 'hover',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'primary',
    state: 'active',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'secondary',
    state: 'active',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'success',
    state: 'active',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'warning',
    state: 'active',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'danger',
    state: 'active',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'primary',
    state: 'focus',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'secondary',
    state: 'focus',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'success',
    state: 'focus',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'warning',
    state: 'focus',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'danger',
    state: 'focus',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'primary',
    state: 'default',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'secondary',
    state: 'default',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'success',
    state: 'default',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'warning',
    state: 'default',
  },
  {
    size: 'small',
    label: 'Button',
    type: 'danger',
    state: 'default',
  },
];

export default filledSmallButtons;
