const linkLargeButtons = [
    {
        size: 'large',
        label: 'Button',
        type: 'primary',
        state: 'filled-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'secondary',
        state: 'filled-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'success',
        state: 'filled-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'warning',
        state: 'filled-link',
    },
    {
        size: 'large',
        label: 'Button',    
        type: 'danger',
        state: 'filled-link',
    }, 
    {
        size: 'large',
        label: 'Button',
        type: 'primary',
        state: 'hover-link',
    }, 
    {
        size: 'large',
        label: 'Button',
        type: 'secondary',
        state: 'hover-link',
    },   
    {
        size: 'large',
        label: 'Button',
        type: 'success',
        state: 'hover-link',
    },   
    {
        size: 'large',
        label: 'Button',
        type: 'warning',
        state: 'hover-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'danger',
        state: 'hover-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'primary',
        state: 'active-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'secondary',
        state: 'active-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'success',
        state: 'active-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'warning',
        state: 'active-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'danger',
        state: 'active-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'primary',
        state: 'focus-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'secondary',
        state: 'focus-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'success',
        state: 'focus-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'warning',
        state: 'focus-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'danger',
        state: 'focus-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'primary',
        state: 'default-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'secondary',
        state: 'default-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'success',
        state: 'default-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'warning',
        state: 'default-link',
    },
    {
        size: 'large',
        label: 'Button',
        type: 'danger',
        state: 'default-link',
    },
]

export default linkLargeButtons;
