const outlinedMediumButtons = [
  {
    size: 'medium',
    label: 'Button',
    type: 'primary',
    state: 'filled-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'secondary',
    state: 'filled-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'success',
    state: 'filled-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'warning',
    state: 'filled-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'danger',
    state: 'filled-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'primary',
    state: 'hover-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'secondary',
    state: 'hover-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'success',
    state: 'hover-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'warning',
    state: 'hover-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'danger',
    state: 'hover-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'primary',
    state: 'active-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'secondary',
    state: 'active-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'success',
    state: 'active-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'warning',
    state: 'active-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'danger',
    state: 'active-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'primary',
    state: 'focus-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'secondary',
    state: 'focus-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'success',
    state: 'focus-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'warning',
    state: 'focus-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'danger',
    state: 'focus-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'primary',
    state: 'default-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'secondary',
    state: 'default-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'success',
    state: 'default-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'warning',
    state: 'default-outlined',
  },
  {
    size: 'medium',
    label: 'Button',
    type: 'danger',
    state: 'default-outlined',
  },
];

export default outlinedMediumButtons;
